### ISSUE TITLE
Running out of bounds.

### ISSUE THREAD

**Issue by kurtwheeler** [ayaigame/ayai-backend#65]
Running all the way to the right of a screen crashes the server.

Stack trace:

java.lang.ArrayIndexOutOfBoundsException: 60
    at ayai.components.TileMap.getTileByPosition(TileMap.scala:33)
    at ayai.components.TileMap.onTileCollision(TileMap.scala:59)
    at ayai.systems.MovementSystem.processEntity(MovementSystem.scala:45)
    at crane.EntityProcessingSystem.process(System.scala:19)
    at crane.World$$anonfun$process$1$$anonfun$apply$mcVI$sp$1.apply(World.scala:197)
    at crane.World$$anonfun$process$1$$anonfun$apply$mcVI$sp$1.apply(World.scala:195)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
    at crane.World.process(World.scala:194)
    at ayai.apps.GameLoop$.main(GameLoop.scala:114)
    at ayai.apps.GameLoop.main(GameLoop.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)

**Comment by timothyhahn** [comment]
Fixed by me :) :+1:
